version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: searcher_property_db
    networks:
      - search-app-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - search-app-network

networks:
  search-app-network:
    driver: bridge