CREATE TABLE category
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    active         BOOLEAN                                 NOT NULL,
    insert_user_id BIGINT,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    updated_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE category_contexts
(
    category_id BIGINT NOT NULL,
    contexts_id BIGINT NOT NULL
);

CREATE TABLE category_properties
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value        VARCHAR(255)                            NOT NULL,
    active       BOOLEAN,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_category_properties PRIMARY KEY (id)
);

CREATE TABLE category_property_category
(
    category_id          BIGINT NOT NULL,
    category_property_id BIGINT NOT NULL
);

CREATE TABLE context
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    insert_user_id BIGINT,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    updated_date   TIMESTAMP WITHOUT TIME ZONE,
    active         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_context PRIMARY KEY (id)
);

CREATE TABLE images_addresses
(
    product_id       BIGINT NOT NULL,
    images_addresses VARCHAR(255)
);

CREATE TABLE product
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    description     VARCHAR(255),
    price           DECIMAL,
    category        VARCHAR(255),
    shop_name       VARCHAR(255),
    product_address VARCHAR(255),
    context_id      BIGINT,
    created_date    TIMESTAMP WITHOUT TIME ZONE,
    updated_date    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE shop
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    country        VARCHAR(255),
    context_id     BIGINT,
    insert_user_id BIGINT,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    updated_date   TIMESTAMP WITHOUT TIME ZONE,
    active         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_shop PRIMARY KEY (id)
);

CREATE TABLE shop_contexts (
  shop_id BIGINT NOT NULL,
  context_id BIGINT NOT NULL
);

CREATE TABLE shop_attribute
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shop_id        BIGINT,
    context_id     BIGINT,
    name           VARCHAR(255)                            NOT NULL,
    value          VARCHAR(255),
    insert_user_id BIGINT,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    updated_date   TIMESTAMP WITHOUT TIME ZONE,
    active         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_shop_attribute PRIMARY KEY (id)
);

CREATE TABLE shop_attribute_shop(
  shop_attribute_id BIGINT NOT NULL,
  shop_id BIGINT NOT NULL
);

CREATE TABLE shop_attribute_context(
  shop_attribute_id BIGINT NOT NULL,
  context_id BIGINT NOT NULL
);

ALTER TABLE shop_attribute_shop
    ADD CONSTRAINT fk_shop_attribute_shop_on_shop_attribute FOREIGN KEY (shop_attribute_id) REFERENCES shop_attribute (id);

ALTER TABLE shop_attribute_shop
    ADD CONSTRAINT fk_shop_attribute_shop_on_shop FOREIGN KEY (shop_id) REFERENCES shop (id);

ALTER TABLE shop_attribute_context
    ADD CONSTRAINT fk_shop_attribute_context_on_shop_attribute FOREIGN KEY (shop_attribute_id) REFERENCES shop_attribute (id);

ALTER TABLE shop_attribute_context
    ADD CONSTRAINT fk_shop_attribute_context_on_context FOREIGN KEY (context_id) REFERENCES context (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CONTEXT FOREIGN KEY (context_id) REFERENCES context (id);

ALTER TABLE shop_attribute
    ADD CONSTRAINT FK_SHOP_ATTRIBUTE_ON_CONTEXT FOREIGN KEY (context_id) REFERENCES context (id);

ALTER TABLE shop_attribute
    ADD CONSTRAINT FK_SHOP_ATTRIBUTE_ON_SHOP FOREIGN KEY (shop_id) REFERENCES shop (id);

ALTER TABLE shop
    ADD CONSTRAINT FK_SHOP_ON_CONTEXT FOREIGN KEY (context_id) REFERENCES context (id);

ALTER TABLE category_contexts
    ADD CONSTRAINT fk_catcon_on_category FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE category_contexts
    ADD CONSTRAINT fk_catcon_on_context FOREIGN KEY (contexts_id) REFERENCES context (id);

ALTER TABLE category_property_category
    ADD CONSTRAINT fk_catprocat_on_category FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE category_property_category
    ADD CONSTRAINT fk_catprocat_on_category_property FOREIGN KEY (category_property_id) REFERENCES category_properties (id);

ALTER TABLE images_addresses
    ADD CONSTRAINT fk_images_addresses_on_product FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE shop_contexts
    ADD CONSTRAINT fk_shop_contexts_on_context FOREIGN KEY (context_id) REFERENCES context (id);

ALTER TABLE shop_contexts
    ADD CONSTRAINT fk_shop_contexts_on_shop FOREIGN KEY (shop_id) REFERENCES shop (id);